### ISSUE TITLE
Address count divergence in statistics endpoint

### ISSUE THREAD

**Issue by lopescode** [CityOfZion/dora#665] opened 2024-10-07 15:29 UTC
Hey guys, how's it going?

I have noticed a divergence in the statistics endpoint compared to what is displayed in the x explorer.

https://dora.coz.io/api/neox/mainnet/stats

Could you help me investigate what might be going on?

I've made a request now and the `total_addresses` replied was 1230.

```json
{
    "average_block_time": 18404.0,
    "coin_image": null,
    "coin_price": null,
    "coin_price_change_percentage": null,
    "gas_price_updated_at": "2024-10-07T15:03:30.617789Z",
    "gas_prices": {
        "slow": 37.5,
        "average": 37.5,
        "fast": 37.5
    },
    "gas_prices_update_in": 22861,
    "gas_used_today": "31286302",
    "market_cap": "0",
    "network_utilization_percentage": 0.008148666666666667,
    "secondary_coin_price": null,
    "static_gas_price": null,
    "total_addresses": "1230",
    "total_blocks": "471002",
    "total_gas_used": "0",
    "total_transactions": "7388",
    "transactions_today": "135",
    "tvl": null
}
```

Taking a look into the x explorer the displayed addresses count is 1363

![image](https://github.com/user-attachments/assets/ec295e57-7952-46a0-838c-f980c2daa6ee)

**Comment by revett** [comment] 2024-10-07 16:16
Thanks for the issue @lopescode 👍 

This is a duplicate of https://github.com/CityOfZion/neox-blockscout/issues/39.

**Closed as completed by revett** 2024-10-07 16:16 UTC
